/**
 * Generate env.js runtime config files from the project root .env file.
 *
 * Usage:
 *   node scripts/generate-env.js
 *
 * This script reads FIREBASE_* variables from .env and writes env.js to:
 *   - env.js (project root)
 *   - firebase-public/env.js
 *   - mobile-app/www/env.js
 *   - mobile-app/android/app/src/main/assets/public/env.js
 *
 * Never commit the generated env.js files or .env to version control.
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');

if (!fs.existsSync(envPath)) {
  console.error(`Missing .env file at ${envPath}`);
  console.error('Copy .env.example to .env and fill in your values, then run this script again.');
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf8');
const vars = {};
envContent.split(/\r?\n/).forEach(line => {
  const match = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.*?)\s*$/);
  if (match) {
    vars[match[1]] = match[2];
  }
});

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID'
];

const missing = required.filter(k => !vars[k]);
if (missing.length) {
  console.warn(`Warning: missing Firebase env variables: ${missing.join(', ')}`);
}

const firebaseConfig = {
  apiKey: vars.FIREBASE_API_KEY || '',
  authDomain: vars.FIREBASE_AUTH_DOMAIN || '',
  projectId: vars.FIREBASE_PROJECT_ID || '',
  storageBucket: vars.FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: vars.FIREBASE_MESSAGING_SENDER_ID || '',
  appId: vars.FIREBASE_APP_ID || ''
};

const output = `// Generated by scripts/generate-env.js — DO NOT EDIT MANUALLY
// Source: project root .env
// This file is ignored by git; do not commit it.

window.ENV = {
  FIREBASE_CONFIG: ${JSON.stringify(firebaseConfig, null, 2)},
  PAD_API_URL: ${JSON.stringify(vars.PAD_API_URL || 'http://localhost:3001')}
};
`;

const targets = [
  'env.js',
  'firebase-public/env.js',
  'mobile-app/www/env.js',
  'mobile-app/android/app/src/main/assets/public/env.js'
];

targets.forEach(target => {
  const targetPath = path.join(rootDir, target);
  const targetDir = path.dirname(targetPath);
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  fs.writeFileSync(targetPath, output);
  console.log(`Generated ${target}`);
});

console.log('env.js generation complete.');
